CREATE OR REPLACE PROCEDURE DIM_INCOME_BAND_SP(TABLE_NAME VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS
DECLARE

V_START_TIME TIMESTAMP;
V_END_TIME TIMESTAMP;

V_SOURCE_TABLE_NAME VARCHAR;
V_TARGET_TABLE_NAME VARCHAR;

V_SOURCE_RECORD_COUNT NUMBER(10);
V_TARGET_RECORD_COUNT NUMBER(10);

BEGIN

LET V_STARTING_PROC := CURRENT_TIMESTAMP();

------------------------------------------------------------
-- STEP 1 : SOURCE → STAGE
------------------------------------------------------------

V_START_TIME := CURRENT_TIMESTAMP();

V_SOURCE_TABLE_NAME :=
    'SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.' || TABLE_NAME;

V_TARGET_TABLE_NAME :=
    'EDW_SRC.PUBLIC.STAGE_' || TABLE_NAME;

SELECT COUNT(1)
INTO :V_SOURCE_RECORD_COUNT
FROM IDENTIFIER(:V_SOURCE_TABLE_NAME);

LET Q_STAGE_DELETE :=
    'TRUNCATE TABLE EDW_SRC.PUBLIC.STAGE_' || TABLE_NAME;

EXECUTE IMMEDIATE Q_STAGE_DELETE;

LET Q_STAGE_INSERT :=
    'INSERT INTO EDW_SRC.PUBLIC.STAGE_' || TABLE_NAME || '
    SELECT
        IB_INCOME_BAND_SK,
        IB_LOWER_BOUND,
        IB_UPPER_BOUND
    FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.' || TABLE_NAME;

EXECUTE IMMEDIATE Q_STAGE_INSERT;

SELECT COUNT(1)
INTO :V_TARGET_RECORD_COUNT
FROM IDENTIFIER(:V_TARGET_TABLE_NAME);

V_END_TIME := CURRENT_TIMESTAMP();

INSERT INTO EDW_SRC.PUBLIC.EDW_AUDIT_LOG
(
    SOURCE_TABLE_NAME,
    TARGET_TABLE_NAME,
    SOURCE_RECORD_COUNT,
    TARGET_RECORD_COUNT,
    START_TIME,
    END_TIME,
    JOB_STATUS,
    REASON_FOR_FAILURE
)
VALUES
(
    :V_SOURCE_TABLE_NAME,
    :V_TARGET_TABLE_NAME,
    :V_SOURCE_RECORD_COUNT,
    :V_TARGET_RECORD_COUNT,
    :V_START_TIME,
    :V_END_TIME,
    'Success',
    NULL
);

------------------------------------------------------------
-- STEP 2 : STAGE → STAGE_DERIVED
------------------------------------------------------------

V_START_TIME := CURRENT_TIMESTAMP();

V_SOURCE_TABLE_NAME :=
    'EDW_SRC.PUBLIC.STAGE_' || TABLE_NAME;

V_TARGET_TABLE_NAME :=
    'EDW_SRC.PUBLIC.STAGE_' || TABLE_NAME || '_DERIVED';

SELECT COUNT(1)
INTO :V_SOURCE_RECORD_COUNT
FROM IDENTIFIER(:V_SOURCE_TABLE_NAME);

LET Q_DERIVED_DELETE :=
    'TRUNCATE TABLE EDW_SRC.PUBLIC.STAGE_' ||
    TABLE_NAME || '_DERIVED';

EXECUTE IMMEDIATE Q_DERIVED_DELETE;

LET Q_DERIVED_INSERT :=
    'INSERT INTO EDW_SRC.PUBLIC.STAGE_' || TABLE_NAME || '_DERIVED
    SELECT
        CURRENT_TIMESTAMP() AS INSERT_GMT_TIMESTAMP,
        CURRENT_TIMESTAMP() AS UPDATE_GMT_TIMESTAMP,
        TO_NUMBER(TO_CHAR(CURRENT_DATE(), ''YYYYMMDD'')) AS LOAD_DATE,
        TO_NUMBER(TO_CHAR(CURRENT_DATE(), ''YYYYMMDDHH24MISS'')) AS LOAD_IDENTIFIER,
        IB_INCOME_BAND_SK,
        IB_LOWER_BOUND,
        IB_UPPER_BOUND
    FROM EDW_SRC.PUBLIC.STAGE_' || TABLE_NAME;

EXECUTE IMMEDIATE Q_DERIVED_INSERT;

SELECT COUNT(1)
INTO :V_TARGET_RECORD_COUNT
FROM IDENTIFIER(:V_TARGET_TABLE_NAME);

V_END_TIME := CURRENT_TIMESTAMP();

INSERT INTO EDW_SRC.PUBLIC.EDW_AUDIT_LOG
(
    SOURCE_TABLE_NAME,
    TARGET_TABLE_NAME,
    SOURCE_RECORD_COUNT,
    TARGET_RECORD_COUNT,
    START_TIME,
    END_TIME,
    JOB_STATUS,
    REASON_FOR_FAILURE
)
VALUES
(
    :V_SOURCE_TABLE_NAME,
    :V_TARGET_TABLE_NAME,
    :V_SOURCE_RECORD_COUNT,
    :V_TARGET_RECORD_COUNT,
    :V_START_TIME,
    :V_END_TIME,
    'Success',
    NULL
);

------------------------------------------------------------
-- STEP 3 : STAGE_DERIVED → DIM
------------------------------------------------------------

V_START_TIME := CURRENT_TIMESTAMP();

V_SOURCE_TABLE_NAME :=
    'EDW_SRC.PUBLIC.STAGE_' || TABLE_NAME || '_DERIVED';

V_TARGET_TABLE_NAME :=
    'EDW_SRC.PUBLIC.DIM_' || TABLE_NAME;

SELECT COUNT(1)
INTO :V_SOURCE_RECORD_COUNT
FROM IDENTIFIER(:V_SOURCE_TABLE_NAME);

LET Q_DIM_DELETE :=
    'DELETE FROM EDW_SRC.PUBLIC.DIM_' || TABLE_NAME ||
    ' WHERE IB_INCOME_BAND_SK IN
      (
          SELECT DISTINCT IB_INCOME_BAND_SK
          FROM EDW_SRC.PUBLIC.STAGE_' || TABLE_NAME || '_DERIVED
      )';

EXECUTE IMMEDIATE Q_DIM_DELETE;

LET Q_DIM_INSERT :=
    'INSERT INTO EDW_SRC.PUBLIC.DIM_' || TABLE_NAME || '
    SELECT
        CURRENT_TIMESTAMP() AS INSERT_GMT_TIMESTAMP,
        CURRENT_TIMESTAMP() AS UPDATE_GMT_TIMESTAMP,
        TO_NUMBER(TO_CHAR(CURRENT_DATE(), ''YYYYMMDD'')) AS LOAD_DATE,
        TO_NUMBER(TO_CHAR(CURRENT_DATE(), ''YYYYMMDDHH24MISS'')) AS LOAD_IDENTIFIER,
        IB_INCOME_BAND_SK,
        IB_LOWER_BOUND,
        IB_UPPER_BOUND
    FROM EDW_SRC.PUBLIC.STAGE_' || TABLE_NAME || '_DERIVED';

EXECUTE IMMEDIATE Q_DIM_INSERT;

SELECT COUNT(1)
INTO :V_TARGET_RECORD_COUNT
FROM IDENTIFIER(:V_TARGET_TABLE_NAME);

V_END_TIME := CURRENT_TIMESTAMP();

INSERT INTO EDW_SRC.PUBLIC.EDW_AUDIT_LOG
(
    SOURCE_TABLE_NAME,
    TARGET_TABLE_NAME,
    SOURCE_RECORD_COUNT,
    TARGET_RECORD_COUNT,
    START_TIME,
    END_TIME,
    JOB_STATUS,
    REASON_FOR_FAILURE
)
VALUES
(
    :V_SOURCE_TABLE_NAME,
    :V_TARGET_TABLE_NAME,
    :V_SOURCE_RECORD_COUNT,
    :V_TARGET_RECORD_COUNT,
    :V_START_TIME,
    :V_END_TIME,
    'Success',
    NULL
);

------------------------------------------------------------
-- PROCEDURE COMPLETION
------------------------------------------------------------

LET V_ENDING_PROC := CURRENT_TIMESTAMP();

RETURN 'PROCEDURE SUCCESSFULLY COMPLETED' ||
       ' START_TIME :' || V_STARTING_PROC ||
       ' END TIME :' || V_ENDING_PROC;

------------------------------------------------------------
-- EXCEPTION HANDLING
------------------------------------------------------------

EXCEPTION

WHEN OTHER THEN

    INSERT INTO EDW_SRC.PUBLIC.EDW_AUDIT_LOG
    (
        SOURCE_TABLE_NAME,
        TARGET_TABLE_NAME,
        SOURCE_RECORD_COUNT,
        TARGET_RECORD_COUNT,
        START_TIME,
        END_TIME,
        JOB_STATUS,
        REASON_FOR_FAILURE
    )
    VALUES
    (
        :V_SOURCE_TABLE_NAME,
        :V_TARGET_TABLE_NAME,
        :V_SOURCE_RECORD_COUNT,
        :V_TARGET_RECORD_COUNT,
        :V_START_TIME,
        :V_END_TIME,
        'FAILED',
        :SQLERRM
    );

    RETURN 'DIM INCOME BAND PROCEDURE FAILED';

END;


#Call the procedure
CALL DIM_INCOME_BAND_SP('INCOME_BAND');


#Verify final Dimension table
SELECT *
FROM EDW_SRC.PUBLIC.DIM_INCOME_BAND;

#Verify Stage table
SELECT *
FROM EDW_SRC.PUBLIC.STAGE_INCOME_BAND;


#Verify Derived table
SELECT *
FROM EDW_SRC.PUBLIC.STAGE_INCOME_BAND_DERIVED;

#Verify audit records
SELECT *
FROM EDW_SRC.PUBLIC.EDW_AUDIT_LOG
ORDER BY START_TIME;


#Check record counts directly
SELECT COUNT(*) AS SOURCE_COUNT
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.INCOME_BAND;

SELECT COUNT(*) AS STAGE_COUNT
FROM EDW_SRC.PUBLIC.STAGE_INCOME_BAND;

SELECT COUNT(*) AS DERIVED_COUNT
FROM EDW_SRC.PUBLIC.STAGE_INCOME_BAND_DERIVED;

SELECT COUNT(*) AS DIM_COUNT
FROM EDW_SRC.PUBLIC.DIM_INCOME_BAND;